name = input("Enter your name: ")
age = int(input("Enter your age: "))
favorite_color = input("Enter your favorite color: ")
favorite_movie = input("Enter your favorite movie: ")
mobNum = input("Enter your mobile number: ")
motto = input("What is your motto in life? ")
